# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: UseDotNet@2
  displayName: Use .NET 8.0
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet tool restore
  displayName: 'Restore Tools'

- script: dotnet cake --target=UpdateVersion
  displayName: 'GitVersion'

- script: dotnet cake --target=DockerBuild
  displayName: 'Docker Build'

- script: dotnet cake --target=DockerPack
  displayName: 'Docker Pack'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Docker Images'
  inputs:
    PathtoPublish: './output/docker/'
    ArtifactName: 'docker'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Swarm Deployment Artifacts'
  inputs:
    PathtoPublish: './output/deployment/swarm'
    ArtifactName: 'deployment-swarm'
    publishLocation: 'Container'